name: Go Test and Local Coverage Badge

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.0'  # specify the Go version you need

      - name: Install dependencies
        run: go mod download

      - name: Run tests with coverage
        run: go test -coverprofile=coverage.out ./...

      - name: Generate Coverage Report
        run: |
          go tool cover -func=coverage.out -o coverage.txt
          go tool cover -html=coverage.out -o coverage.html
          echo "Coverage report generated"

      - name: Create Coverage Badge
        run: |
          go install github.com/matm/gocovsh@latest
          gocovsh badge -coverprofile=coverage.out -o coverage_badge.svg

      - name: Upload Badge
        uses: actions/upload-artifact@v3
        with:
          name: coverage-badge
          path: coverage_badge.svg

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Change if you want to publish from a specific directory
          publish_branch: gh-pages  # This is the branch where GitHub Pages serves content
          destination_dir: .  # Publish to the root of the `gh-pages` branch
          force_orphan: true  # Create an orphan branch if needed
          
      - name: Commit and Push Coverage Badge
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add coverage_badge.svg
          git commit -m 'Update coverage badge'
          git push -f origin gh-pages